2013/02/05 09:51:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'praktik.tbl_users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_users`.
in C:\xampp\htdocs\Yii\index.php (13)
2013/02/05 10:29:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\Yii\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\Yii\protected\controllers\UsersController.php(55): UsersController->loadModel('120')
#1 [internal function]: UsersController->actionView('120')
#2 C:\xampp\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Yii/index.php?r=users/view&id=120
HTTP_REFERER=http://localhost/Yii/index.php?r=users/create
---
2013/02/05 10:29:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\Yii\protected\controllers\UsersController.php:157
Stack trace:
#0 C:\xampp\htdocs\Yii\protected\controllers\UsersController.php(55): UsersController->loadModel('120')
#1 [internal function]: UsersController->actionView('120')
#2 C:\xampp\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#3 C:\xampp\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#4 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/view')
#14 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Yii/index.php?r=users/view&id=120
HTTP_REFERER=http://localhost/Yii/index.php?r=users/create
---
2013/02/05 10:58:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "outbound".' in C:\xampp\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('outbound')
#1 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii/index.php?r=outbound
---
2013/02/05 10:59:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?/r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=documentsOutbound
---
2013/02/05 10:59:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?/r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=documentsOutbound
---
2013/02/05 10:59:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?r=documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?r=doc...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?r=doc...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?/r=documentsOutbound
---
2013/02/05 10:59:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "index.php?r=documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('index.php?r=doc...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('index.php?r=doc...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php?...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/index.php?r=documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?/r=documentsOutbound
---
2013/02/05 10:59:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index.php?r=documentsOutbound
---
2013/02/05 11:01:16 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbound
---
2013/02/05 11:02:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbounddocumentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:02:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "documentsOutbound".' in C:\xampp\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(270): CController->missingAction('documentsOutbou...')
#1 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('documentsOutbou...')
#2 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/documentsO...')
#3 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii/index.php?r=site/documentsOutbound
HTTP_REFERER=http://localhost/Yii/index.php?r=site/documentsOutbounddocumentsOutbound
---
2013/02/05 11:08:07 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#10 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound/view
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index
---
2013/02/05 11:08:24 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#10 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound/view
HTTP_REFERER=http://localhost/Yii/index.php?r=site/index
---
2013/02/05 12:34:13 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'accesspoint'' in C:\xampp\yii\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CApplication.php(438): CModule->getComponent('db')
#4 C:\xampp\yii\framework\db\ar\CActiveRecord.php(623): CApplication->getDb()
#5 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#7 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#8 C:\xampp\htdocs\Yii\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#9 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#10 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#20 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\index.php(16): CApplication->run()
#22 {main}
REQUEST_URI=/yii/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/yii/
---
2013/02/05 12:34:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'accesspoint'' in C:\xampp\yii\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CApplication.php(438): CModule->getComponent('db')
#4 C:\xampp\yii\framework\db\ar\CActiveRecord.php(623): CApplication->getDb()
#5 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsOutbound))
#7 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsOutbou...')
#8 C:\xampp\htdocs\Yii\protected\controllers\DocumentsOutboundController.php(125): CActiveDataProvider->__construct('DocumentsOutbou...')
#9 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsOutboundController->actionIndex()
#10 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsoutbou...')
#20 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\index.php(16): CApplication->run()
#22 {main}
REQUEST_URI=/yii/index.php?r=documentsoutbound
HTTP_REFERER=http://localhost/yii/
---
2013/02/05 12:34:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'accesspoint'' in C:\xampp\yii\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CApplication.php(438): CModule->getComponent('db')
#4 C:\xampp\yii\framework\db\ar\CActiveRecord.php(623): CApplication->getDb()
#5 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#7 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#8 C:\xampp\htdocs\Yii\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#9 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#10 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#20 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\index.php(16): CApplication->run()
#22 {main}
REQUEST_URI=/yii/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/yii/
---
2013/02/05 12:34:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1049] Unknown database 'accesspoint'' in C:\xampp\yii\framework\db\CDbConnection.php:381
Stack trace:
#0 C:\xampp\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\yii\framework\base\CApplication.php(438): CModule->getComponent('db')
#4 C:\xampp\yii\framework\db\ar\CActiveRecord.php(623): CApplication->getDb()
#5 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2309): CActiveRecord->getDbConnection()
#6 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsOutbound))
#7 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsOutbou...')
#8 C:\xampp\htdocs\Yii\protected\controllers\DocumentsOutboundController.php(125): CActiveDataProvider->__construct('DocumentsOutbou...')
#9 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsOutboundController->actionIndex()
#10 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsoutbou...')
#20 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\index.php(16): CApplication->run()
#22 {main}
REQUEST_URI=/yii/index.php?r=documentsoutbound
HTTP_REFERER=http://localhost/yii/
---
2013/02/05 13:24:34 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsOutbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsOutbou...')
#5 C:\xampp\htdocs\Yii\protected\controllers\DocumentsOutboundController.php(125): CActiveDataProvider->__construct('DocumentsOutbou...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsOutboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsoutbou...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Yii\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/index.php?r=documentsoutbound
HTTP_REFERER=http://localhost/Yii/index.php
---
2013/02/05 13:24:38 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(ScannedDocuments))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('ScannedDocument...')
#5 C:\xampp\htdocs\Yii\protected\controllers\ScannedDocumentsController.php(125): CActiveDataProvider->__construct('ScannedDocument...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): ScannedDocumentsController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('scannedDocument...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Yii\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/index.php?r=scannedDocuments
HTTP_REFERER=http://localhost/Yii/index.php
---
2013/02/05 13:24:40 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#5 C:\xampp\htdocs\Yii\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Yii\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/Yii/index.php
---
2013/02/05 13:27:35 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#5 C:\xampp\htdocs\Yii\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Yii\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/Yii/index.php?r=documentsoutbound
---
2013/02/05 13:39:26 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsOutbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsOutbou...')
#5 C:\xampp\htdocs\Yii\protected\controllers\DocumentsOutboundController.php(125): CActiveDataProvider->__construct('DocumentsOutbou...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsOutboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsoutbou...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Yii\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/Yii/index.php?r=documentsoutbound
HTTP_REFERER=http://localhost/Yii/index.php
---
2013/02/05 14:57:54 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(ScannedDocuments))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('ScannedDocument...')
#5 C:\xampp\htdocs\accesspoint\protected\controllers\ScannedDocumentsController.php(125): CActiveDataProvider->__construct('ScannedDocument...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): ScannedDocumentsController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('scannedDocument...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\accesspoint\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/accesspoint/index.php?r=scannedDocuments
HTTP_REFERER=http://localhost/accesspoint/index.php
---
2013/02/05 14:58:10 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsOutbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsOutbou...')
#5 C:\xampp\htdocs\accesspoint\protected\controllers\DocumentsOutboundController.php(125): CActiveDataProvider->__construct('DocumentsOutbou...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsOutboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsoutbou...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\accesspoint\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/accesspoint/index.php?r=documentsoutbound
HTTP_REFERER=http://localhost/accesspoint/index.php
---
2013/02/05 15:01:38 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#5 C:\xampp\htdocs\accesspoint\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\accesspoint\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/accesspoint/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/accesspoint/index.php?r=documentsoutbound
---
2013/02/06 09:07:58 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(DocumentsInbound))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('DocumentsInboun...')
#5 C:\xampp\htdocs\accesspoint\protected\controllers\DocumentsInboundController.php(125): CActiveDataProvider->__construct('DocumentsInboun...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): DocumentsInboundController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('documentsinboun...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\accesspoint\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/accesspoint/index.php?r=documentsinbound
HTTP_REFERER=http://localhost/accesspoint/index.php
---
2013/02/06 09:08:04 [error] [exception.CException] exception 'CException' with message 'Property "CHasManyRelation.0" is not defined.' in C:\xampp\yii\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\yii\framework\db\ar\CActiveRecord.php(1941): CComponent->__set('0', 'document_table')
#1 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2356): CBaseActiveRelation->__construct('log', 'log', 'document_id', Array)
#2 C:\xampp\yii\framework\db\ar\CActiveRecord.php(2337): CActiveRecordMetaData->addRelation('log', Array)
#3 C:\xampp\yii\framework\db\ar\CActiveRecord.php(387): CActiveRecordMetaData->__construct(Object(ScannedDocuments))
#4 C:\xampp\yii\framework\web\CActiveDataProvider.php(74): CActiveRecord::model('ScannedDocument...')
#5 C:\xampp\htdocs\accesspoint\protected\controllers\ScannedDocumentsController.php(125): CActiveDataProvider->__construct('ScannedDocument...')
#6 C:\xampp\yii\framework\web\actions\CInlineAction.php(49): ScannedDocumentsController->actionIndex()
#7 C:\xampp\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#9 C:\xampp\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#10 C:\xampp\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#11 C:\xampp\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#12 C:\xampp\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#13 C:\xampp\yii\framework\web\CController.php(291): CFilterChain->run()
#14 C:\xampp\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\yii\framework\web\CWebApplication.php(282): CController->run('')
#16 C:\xampp\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('scannedDocument...')
#17 C:\xampp\yii\framework\base\CApplication.php(169): CWebApplication->processRequest()
#18 C:\xampp\htdocs\accesspoint\index.php(14): CApplication->run()
#19 {main}
REQUEST_URI=/accesspoint/index.php?r=scannedDocuments
HTTP_REFERER=http://localhost/accesspoint/index.php
---
